// ── Default allowance factory ──────────────────────────────────────────────
export const defaultAllowance = (overrides = {}) => ({
  enabled: true,
  description: "",
  feePerWeek: "0.00",
  weeklyRate: "0.00",
  shootDayRate: "0.00",
  nonShootDayRate: "0.00",
  capCalculatedAs: "flat_figure",
  currency: "GBP",
  terms: "",
  payablePrep: false,
  payableShoot: true,
  payableWrap: false,
  budgetCode: "",
  tag: "",
  rateCap: "£0.00",
  paidTillDate: "£0.00",
  ...overrides,
});

export const defaultAllowances = {
  boxRental: defaultAllowance({
    budgetCode: "823-58-001", tag: "BOX RENT",
    description: "Box Rental is reduced pro-rata on a 5 day/week basis, for weekly hires. Capped at 50% of Inventory.",
    feePerWeek: "400.00", rateCap: "£57,481.50 (50% of total value)",
    terms: "Box Rental is reduced pro-rata on a 5 day/week basis, for weekly hires. Capped at 50% of Inventory.",
    payablePrep: true, payableShoot: true, payableWrap: true,
  }),
  computer: defaultAllowance({
    budgetCode: "858-58-001", tag: "COMPUTER",
    description: "Computer rental is reduced pro-rata on a 5 day/week basis, for weekly hires",
    feePerWeek: "25.00", capCalculatedAs: "flat_figure", rateCap: "£250.00",
    terms: "Computer rental is reduced pro-rata on a 5 day/week basis, for weekly hires",
    payablePrep: true, payableShoot: true, payableWrap: true,
  }),
  software: defaultAllowance({
    budgetCode: "858-58-002", tag: "SOFTWARE",
    description: "Software subscription allowance for production-required tools",
    feePerWeek: "15.00", rateCap: "£150.00",
    terms: "Software allowance is reduced pro-rata on a 5 day/week basis, for weekly hires",
    payablePrep: true, payableShoot: true, payableWrap: false,
  }),
  equipment: defaultAllowance({
    budgetCode: "823-58-010", tag: "EQUIP",
    description: "Personal equipment rental for specialist tools required on production",
    feePerWeek: "75.00", rateCap: "£750.00",
    terms: "Equipment Rental is reduced pro-rata on a 5 day/week basis, for weekly hires",
    payablePrep: false, payableShoot: true, payableWrap: false,
  }),
  vehicle: defaultAllowance({
    budgetCode: "823-58-051", tag: "VEHICLE",
    feePerWeek: "150.00",
    terms: "Vehicle Rental is reduced pro-rata on a 5 day/week basis, for weekly hires.",
    payablePrep: true, payableShoot: true, payableWrap: true,
  }),
  mobile: defaultAllowance({
    budgetCode: "858-58-005", tag: "MOBILE",
    description: "Mobile phone allowance",
    feePerWeek: "10.00", rateCap: "£100.00",
    terms: "Mobile allowance is flat rate per week",
    payablePrep: true, payableShoot: true, payableWrap: true,
  }),
  living: defaultAllowance({
    budgetCode: "823-58-030", tag: "LIVING", currency: "GBP",
    description: "Living allowance for crew based away from home",
    feePerWeek: "200.00", rateCap: "£2,000.00",
    terms: "Living allowance paid weekly for crew working 40+ miles from home address",
    payablePrep: true, payableShoot: true, payableWrap: true,
  }),
  perDiem1: defaultAllowance({
    budgetCode: "823-58-020", tag: "PER DIEM", currency: "GBP",
    description: "Per Diem — UK location shoot days",
    feePerWeek: "50.00", shootDayRate: "50.00", nonShootDayRate: "25.00",
    rateCap: "£350.00",
    terms: "Payable per qualifying day on location. Non-shoot days at 50%.",
    payablePrep: false, payableShoot: true, payableWrap: false,
  }),
  perDiem2: defaultAllowance({
    budgetCode: "823-58-021", tag: "PER DIEM 2", currency: "USD",
    description: "Per Diem — overseas location",
    feePerWeek: "75.00", rateCap: "£525.00",
    terms: "Payable per qualifying day overseas. Subject to receipts.",
    payablePrep: false, payableShoot: true, payableWrap: false,
  }),
  breakfast: defaultAllowance({
    enabled: false, budgetCode: "823-58-040", tag: "BRKFAST",
    description: "Breakfast allowance when not catered",
    feePerWeek: "0.00", shootDayRate: "8.50", rateCap: "£8.50/day",
    terms: "Payable when breakfast is not provided by production catering",
    payablePrep: false, payableShoot: true, payableWrap: false,
  }),
  lunch: defaultAllowance({
    enabled: false, budgetCode: "823-58-041", tag: "LUNCH",
    description: "Lunch allowance when not catered",
    feePerWeek: "0.00", shootDayRate: "12.00", rateCap: "£12.00/day",
    terms: "Payable when lunch is not provided by production catering",
    payablePrep: false, payableShoot: true, payableWrap: false,
  }),
  dinner: defaultAllowance({
    enabled: false, budgetCode: "823-58-042", tag: "DINNER",
    description: "Dinner/late meal allowance",
    feePerWeek: "0.00", shootDayRate: "15.00", rateCap: "£15.00/day",
    terms: "Payable when wrap exceeds 12 hours and dinner not provided",
    payablePrep: false, payableShoot: true, payableWrap: false,
  }),
  fuel: defaultAllowance({
    enabled: false, budgetCode: "823-58-050", tag: "FUEL",
    description: "Fuel reimbursement for production travel",
    feePerWeek: "0.00", rateCap: "Receipts",
    terms: "Fuel reimbursed on receipts for journeys to/from location exceeding 20 miles",
    payablePrep: true, payableShoot: true, payableWrap: true,
  }),
  mileage: defaultAllowance({
    enabled: false, budgetCode: "823-58-052", tag: "MILEAGE",
    description: "Mileage allowance at HMRC approved rate",
    feePerWeek: "0.00", rateCap: "£0.45/mile",
    terms: "HMRC approved mileage rate for business travel using personal vehicle",
    payablePrep: true, payableShoot: true, payableWrap: true,
  }),
};