// defaults.js — static defaults extracted from ContractForm

export const DEFAULT_SCHEDULE = {
  hiatus: [{ start: "", end: "", reason: "" }],
  prePrep: { start: "", end: "", notes: "" },
  blocks: [
    { name: "BLOCK 1", prep: { start: "", end: "", notes: "" }, start: "", end: "", notes: "" },
  ],
  wrap: { start: "", end: "", notes: "" },
  totalDays: 0,
};

export const DEFAULT_DEPARTMENTS = [
  "Accounts","Action Vehicles","Aerial","Animals","Animation","Armoury","Art","Assets",
  "Assistant Directors","Camera","Cast","Chaperones","Choreography","Clearances",
  "Computer Graphics","Construction","Continuity","Costume","Costume FX","Covid Safety",
  "Creature Effects","DIT","Digital Assets","Digital Playback","Director","Documentary",
  "Drapes","EPK","Editorial","Electrical","Electrical Rigging","Franchise","Greens",
  "Greenscreens","Grip","Hair and Makeup","Health and Safety","IT","Locations","Marine",
  "Medical","Military","Music","Photography","Picture Vehicles","Post Production",
  "Production","Prop Making","Props","Prosthetics","Publicity","Puppeteer","Rigging",
  "SFX","Script","Script Editing","Security","Set Dec","Sound","Standby","Storyboard",
  "Studio Unit","Stunts","Supporting Artist","Sustainability","Transport","Tutors",
  "Underwater","VFX","Video","Voice",
];

export const DEFAULT_JOB_TITLES = [
  "1st AC (SELF-EMPLOYED)","1st AC - A Camera (SELF-EMPLOYED)","1st AC - B Camera (SELF-EMPLOYED)",
  "1st Assistant Accountant (PAYE)","1st Assistant Director (SELF-EMPLOYED)",
  "1st Assistant Editor (SELF-EMPLOYED)","1st Boom Operator (SELF-EMPLOYED)",
  "2nd Assistant Director (SELF-EMPLOYED)","2nd Assistant Editor (PAYE)",
  "3D Concept Art Director (SELF-EMPLOYED)","3D Modeller (SELF-EMPLOYED)",
  "3rd Assistant Director (PAYE)","Accountant (PAYE)","Accountant (SELF-EMPLOYED)",
  "Action Props Master (SELF-EMPLOYED)","Action Vehicles Co-ordinator (SELF-EMPLOYED)",
  "Actor (PAYE)","Additional 1st AD (SELF-EMPLOYED)","Admin Assistant (PAYE)",
  "Aerial Coordinator (SELF-EMPLOYED)","Aerial DOP (SELF-EMPLOYED)",
  "Animal Trainer (SELF-EMPLOYED)","Animator (SELF-EMPLOYED)",
  "Armourer (SELF-EMPLOYED)","Art Department Co-ordinator (PAYE)",
  "Art Director (SELF-EMPLOYED)","Assembly Editor (SELF-EMPLOYED)",
  "Assistant Accountant (PAYE)","Assistant Art Director (SELF-EMPLOYED)",
  "Assistant Buyer (PAYE)","Assistant Costume Designer (SELF-EMPLOYED)",
  "Assistant Director - Children (PAYE)","Assistant Editor (PAYE)",
  "Assistant Location Manager (PAYE)","Assistant Production Coordinator (PAYE)",
  "Best Boy (ELECTRICAL SELF-EMPLOYED)","Best Boy Grip (SELF-EMPLOYED)",
  "Boom Operator (SELF-EMPLOYED)","Camera Operator (SELF-EMPLOYED)",
  "Carpenter (CONSTRUCTION SELF-EMPLOYED)","Casting Director (SELF-EMPLOYED)",
  "Chaperone (SELF-EMPLOYED)","Choreographer (SELF-EMPLOYED)",
  "Concept Artist (SELF-EMPLOYED)","Construction Manager (SELF-EMPLOYED)",
  "Costume Designer (SELF-EMPLOYED)","Costume Supervisor (SELF-EMPLOYED)",
  "DOP (SELF-EMPLOYED)","Director (SELF-EMPLOYED)",
  "Editor (SELF-EMPLOYED)","Electrician (ELECTRICAL SELF-EMPLOYED)",
  "Executive Producer (SELF-EMPLOYED)","Fight Coordinator (SELF-EMPLOYED)",
  "Financial Controller (SELF-EMPLOYED)","Floor Runner (PAYE)",
  "Gaffer (ELECTRICAL SELF-EMPLOYED)","Graphic Designer (SELF-EMPLOYED)",
  "Grip (SELF-EMPLOYED)","Hair and Makeup Artist (SELF-EMPLOYED)",
  "Hair and Makeup Designer (SELF-EMPLOYED)","Health and Safety Advisor (SELF-EMPLOYED)",
  "Key Grip (SELF-EMPLOYED)","Line Producer (SELF-EMPLOYED)",
  "Location Manager (PAYE)","Makeup Artist (SELF-EMPLOYED)",
  "Medic (SELF-EMPLOYED)","Model Maker (SELF-EMPLOYED)",
  "Music Editor (SELF-EMPLOYED)","Nurse (SELF-EMPLOYED)",
  "Painter (CONSTRUCTION SELF-EMPLOYED)","Photographer (SELF-EMPLOYED)",
  "Post Production Coordinator (PAYE)","Post Production Supervisor (SELF-EMPLOYED)",
  "Producer (SELF-EMPLOYED)","Production Accountant (SELF-EMPLOYED)",
  "Production Buyer (SELF-EMPLOYED)","Production Coordinator (PAYE)",
  "Production Designer (SELF-EMPLOYED)","Production Manager (SELF-EMPLOYED)",
  "Production Runner (PAYE)","Production Sound Mixer (SELF-EMPLOYED)",
  "Property Master (SELF-EMPLOYED)","Prosthetics Make Up Artist (SELF-EMPLOYED)",
  "Publicist (SELF-EMPLOYED)","Runner (PAYE)",
  "SFX Supervisor (SELF-EMPLOYED)","SFX Technician (SELF-EMPLOYED)",
  "Script Supervisor (SELF-EMPLOYED)","Sculptor (SELF-EMPLOYED)",
  "Set Decorator (SELF-EMPLOYED)","Set Designer (SELF-EMPLOYED)",
  "Sound Mixer (SELF-EMPLOYED)","Standby Props (SELF-EMPLOYED)",
  "Steadicam Operator (SELF-EMPLOYED)","Stills Photographer (SELF-EMPLOYED)",
  "Storyboard Artist (SELF-EMPLOYED)","Stunt Coordinator (SELF-EMPLOYED)",
  "Stunt Performer (SELF-EMPLOYED)","Transport Captain (SELF-EMPLOYED)",
  "Transport Manager (SELF-EMPLOYED)","Unit Manager (SELF-EMPLOYED)",
  "VFX Editor (SELF-EMPLOYED)","VFX Producer (SELF-EMPLOYED)",
  "VFX Supervisor (SELF-EMPLOYED)","Video Operator (SELF-EMPLOYED)",
  "Wardrobe Supervisor (SELF-EMPLOYED)","Orchestrator and Conductor (SELF-EMPLOYED)",
];