import {
  Calendar,
  FileText,
  Clapperboard,
  Archive,
  Shirt,
  UtensilsCrossed,
  DollarSign,
  ScrollText,
  ShoppingCart,
  Truck,
  Play,
  ClipboardList,
  Package,
  PawPrint,
  Car,
  MapPin,
  Cloud,
  Clock,
  Megaphone,
  MessageSquare,
  FileSearch,
  BarChart2,
  Star,
  UserCheck,
  CalendarDays,
  Wallet,
  FolderOpen,
  PenLine,
  Settings2,
  Contact,
  Bookmark,
  Users,
  Building,
  FileBox,
  FileCheck,
  LockKeyhole,
  Sliders,
  Bell,
  CreditCard,
  Palette,
  LayoutGrid,
  AppWindow,
  MessageCircle,
  Brain,
  Film,
  Mic,
  Camera,
  BookOpen,
  Image,
  Video,
  Lightbulb,
  Headphones,
  Music,
} from "lucide-react";

export const AVATAR1_APPS = [
  {
    id: "project-calendar",
    name: "CALENDAR",
    icon: Calendar,
    description: "Master production timeline & milestones",
    notifications: 3,
  },
  {
    id: "call-sheets",
    name: "CALL SHEETS",
    icon: FileText,
    description: "Daily call sheets & crew notifications",
    notifications: 7,
  },
  {
    id: "shooting-schedule",
    name: "SHOOTING SCHEDULE",
    icon: Clapperboard,
    description: "Day-by-day shooting plan & scene order",
    notifications: 2,
  },
  {
    id: "asset",
    name: "ASSET",
    icon: Archive,
    description: "Track & manage all production assets",
  },
  {
    id: "costume",
    name: "COSTUME",
    icon: Shirt,
    description: "Wardrobe tracking & fitting schedules",
    notifications: 1,
  },
  {
    id: "catering",
    name: "CATERING",
    icon: UtensilsCrossed,
    description: "Meal planning & dietary requirements",
  },
  {
    id: "accounts",
    name: "ACCOUNTS",
    icon: DollarSign,
    description: "Financial tracking & expense management",
    notifications: 5,
  },
  {
    id: "script",
    name: "SCRIPT",
    icon: ScrollText,
    description: "Script versions, revisions & annotations",
    notifications: 1,
  },
  {
    id: "market",
    name: "MARKET",
    icon: ShoppingCart,
    description: "Equipment & supply procurement",
  },
  {
    id: "transport",
    name: "TRANSPORT",
    icon: Truck,
    description: "Vehicle scheduling & logistics",
  },
  {
    id: "eplayer",
    name: "E PLAYER",
    icon: Play,
    description: "Dailies playback & review platform",
  },
  {
    id: "forms",
    name: "FORMS",
    icon: ClipboardList,
    description: "Custom forms, approvals & sign-offs",
  },
  {
    id: "props-assets",
    name: "PROPS",
    icon: Package,
    description: "Props inventory & continuity tracking",
  },
  {
    id: "animals",
    name: "ANIMALS",
    icon: PawPrint,
    description: "Animal wrangling schedules & welfare",
  },
  {
    id: "vehicles",
    name: "VEHICLES",
    icon: Car,
    description: "Picture vehicles & fleet management",
  },
  {
    id: "locations",
    name: "LOCATIONS",
    icon: MapPin,
    description: "Location scouting, permits & maps",
    notifications: 2,
  },
  {
    id: "cloud",
    name: "CLOUD",
    icon: Cloud,
    description: "Cloud storage & file sharing",
  },
  {
    id: "timesheets",
    name: "TIMESHEETS",
    icon: Clock,
    description: "Crew hours, overtime & payroll data",
    notifications: 12,
  },
  {
    id: "notice-board",
    name: "NOTICE BOARD",
    icon: Megaphone,
    description: "Company-wide announcements & updates",
    notifications: 4,
  },
  {
    id: "project-chat",
    name: "PROJECT CHAT",
    icon: MessageSquare,
    description: "Real-time team messaging & channels",
    notifications: 18,
  },
  {
    id: "script-breakdown",
    name: "SCRIPT BREAKDOWN",
    icon: FileSearch,
    description: "Scene-by-scene element breakdowns",
  },
  {
    id: "production-reports",
    name: "PRODUCTION REPORTS",
    icon: BarChart2,
    description: "Daily progress reports & analytics",
    notifications: 1,
  },
  {
    id: "casting-calls",
    name: "CASTING CALLS",
    icon: Star,
    description: "Casting sessions & talent management",
  },
  {
    id: "crew",
    name: "CREW",
    icon: Users,
    description: "Crew database, roles & availability",
    notifications: 3,
  },
  {
    id: "cast",
    name: "CAST",
    icon: UserCheck,
    description: "Cast contracts, schedules & contacts",
  },
  {
    id: "schedule",
    name: "SCHEDULE",
    icon: CalendarDays,
    description: "Overall project schedule & Gantt view",
  },
  {
    id: "budget",
    name: "BUDGET",
    icon: Wallet,
    description: "Budget tracking, actuals & forecasts",
    notifications: 2,
  },
  {
    id: "documents",
    name: "DOCUMENTS",
    icon: FolderOpen,
    description: "Contracts, releases & legal docs",
  },
  {
    id: "eaarth-sign",
    name: "EAARTH SIGN",
    icon: PenLine,
    description: "Digital signatures & document signing",
  },
];

export const projects = [
  {
    id: "avatar-1",
    name: "AVATAR 1",
    subtitle: "Principal Photography",
    color: "#2563eb",
    colorLight: "#eff6ff",
    colorDark: "#1e3a5f",
    colorMid: "#60a5fa",
    progress: 67,
    teamCount: 248,
    apps: AVATAR1_APPS,
  },
  {
    id: "avatar-2",
    name: "AVATAR 2",
    subtitle: "Visual Effects",
    color: "#06b6d4",
    colorLight: "#ecfeff",
    colorDark: "#164e63",
    colorMid: "#67e8f9",
    progress: 82,
    teamCount: 192,
    apps: [
      {
        id: "project-calendar",
        name: "CALENDAR",
        icon: Calendar,
        description: "Master production timeline & milestones",
        notifications: 2,
      },
      {
        id: "schedule",
        name: "SCHEDULE",
        icon: CalendarDays,
        description: "Overall project schedule & Gantt view",
      },
      {
        id: "vfx",
        name: "VFX",
        icon: Lightbulb,
        description: "VFX shot tracking & vendor management",
        notifications: 21,
      },
      {
        id: "eplayer",
        name: "E PLAYER",
        icon: Play,
        description: "Dailies playback & review platform",
        notifications: 8,
      },
      {
        id: "editing",
        name: "EDITING",
        icon: Video,
        description: "Edit timeline, cuts & assembly tracking",
        notifications: 5,
      },
      {
        id: "production-reports",
        name: "PRODUCTION REPORTS",
        icon: BarChart2,
        description: "Daily progress reports & analytics",
        notifications: 3,
      },
      {
        id: "accounts",
        name: "ACCOUNTS",
        icon: DollarSign,
        description: "Financial tracking & expense management",
        notifications: 4,
      },
      {
        id: "budget",
        name: "BUDGET",
        icon: Wallet,
        description: "Budget tracking, actuals & forecasts",
      },
      {
        id: "timesheets",
        name: "TIMESHEETS",
        icon: Clock,
        description: "Crew hours, overtime & payroll data",
        notifications: 9,
      },
      {
        id: "crew",
        name: "CREW",
        icon: Users,
        description: "Crew database, roles & availability",
        notifications: 1,
      },
      {
        id: "notice-board",
        name: "NOTICE BOARD",
        icon: Megaphone,
        description: "Company-wide announcements & updates",
        notifications: 2,
      },
      {
        id: "project-chat",
        name: "PROJECT CHAT",
        icon: MessageSquare,
        description: "Real-time team messaging & channels",
        notifications: 15,
      },
      {
        id: "documents",
        name: "DOCUMENTS",
        icon: FolderOpen,
        description: "Contracts, releases & legal docs",
      },
      {
        id: "cloud",
        name: "CLOUD",
        icon: Cloud,
        description: "Cloud storage & file sharing",
      },
      {
        id: "eaarth-sign",
        name: "EAARTH SIGN",
        icon: PenLine,
        description: "Digital signatures & document signing",
      },
    ],
  },
  {
    id: "avatar-3",
    name: "AVATAR 3",
    subtitle: "Pre-Production",
    color: "#10b981",
    colorLight: "#ecfdf5",
    colorDark: "#065f46",
    colorMid: "#6ee7b7",
    progress: 34,
    teamCount: 86,
    apps: [
      {
        id: "project-calendar",
        name: "CALENDAR",
        icon: Calendar,
        description: "Master production timeline & milestones",
        notifications: 1,
      },
      {
        id: "script",
        name: "SCRIPT",
        icon: ScrollText,
        description: "Script versions, revisions & annotations",
        notifications: 3,
      },
      {
        id: "script-breakdown",
        name: "SCRIPT BREAKDOWN",
        icon: FileSearch,
        description: "Scene-by-scene element breakdowns",
      },
      {
        id: "shooting-schedule",
        name: "SHOOTING SCHEDULE",
        icon: Clapperboard,
        description: "Day-by-day shooting plan & scene order",
      },
      {
        id: "locations",
        name: "LOCATIONS",
        icon: MapPin,
        description: "Location scouting, permits & maps",
        notifications: 5,
      },
      {
        id: "accounts",
        name: "ACCOUNTS",
        icon: DollarSign,
        description: "Financial tracking & expense management",
      },
      {
        id: "budget",
        name: "BUDGET",
        icon: Wallet,
        description: "Budget tracking, actuals & forecasts",
        notifications: 1,
      },
      {
        id: "casting-calls",
        name: "CASTING CALLS",
        icon: Star,
        description: "Casting sessions & talent management",
        notifications: 8,
      },
      {
        id: "cast",
        name: "CAST",
        icon: UserCheck,
        description: "Cast contracts, schedules & contacts",
      },
      {
        id: "crew",
        name: "CREW",
        icon: Users,
        description: "Crew database, roles & availability",
        notifications: 2,
      },
      {
        id: "costume",
        name: "COSTUME",
        icon: Shirt,
        description: "Wardrobe tracking & fitting schedules",
      },
      {
        id: "storyboard",
        name: "STORYBOARD",
        icon: Film,
        description: "Visual storyboards & shot planning",
        notifications: 4,
      },
      {
        id: "concept-art",
        name: "CONCEPT ART",
        icon: Palette,
        description: "Concept artwork & visual references",
      },
      {
        id: "call-sheets",
        name: "CALL SHEETS",
        icon: FileText,
        description: "Daily call sheets & crew notifications",
      },
      {
        id: "notice-board",
        name: "NOTICE BOARD",
        icon: Megaphone,
        description: "Company-wide announcements & updates",
        notifications: 2,
      },
      {
        id: "project-chat",
        name: "PROJECT CHAT",
        icon: MessageSquare,
        description: "Real-time team messaging & channels",
        notifications: 11,
      },
      {
        id: "forms",
        name: "FORMS",
        icon: ClipboardList,
        description: "Custom forms, approvals & sign-offs",
      },
      {
        id: "documents",
        name: "DOCUMENTS",
        icon: FolderOpen,
        description: "Contracts, releases & legal docs",
      },
      {
        id: "cloud",
        name: "CLOUD",
        icon: Cloud,
        description: "Cloud storage & file sharing",
      },
      {
        id: "eaarth-sign",
        name: "EAARTH SIGN",
        icon: PenLine,
        description: "Digital signatures & document signing",
      },
    ],
  },
  {
    id: "avatar-4",
    name: "AVATAR 4",
    subtitle: "Underwater Capture",
    color: "#14b8a6",
    colorLight: "#f0fdfa",
    colorMid: "#5eead4",
    colorDark: "#134e4a",
    progress: 23,
    teamCount: 118,
    apps: [
      {
        id: "project-calendar",
        name: "CALENDAR",
        icon: Calendar,
        description: "Master production timeline & milestones",
        notifications: 4,
      },
      {
        id: "call-sheets",
        name: "CALL SHEETS",
        icon: FileText,
        description: "Daily call sheets & crew notifications",
        notifications: 3,
      },
      {
        id: "shooting-schedule",
        name: "SHOOTING SCHEDULE",
        icon: Clapperboard,
        description: "Day-by-day shooting plan & scene order",
        notifications: 1,
      },
      {
        id: "script",
        name: "SCRIPT",
        icon: ScrollText,
        description: "Script versions, revisions & annotations",
        notifications: 2,
      },
      {
        id: "locations",
        name: "LOCATIONS",
        icon: MapPin,
        description: "Location scouting, permits & maps",
        notifications: 6,
      },
      {
        id: "camera",
        name: "CAMERA",
        icon: Camera,
        description: "Camera equipment & lens tracking",
        notifications: 2,
      },
      {
        id: "cast",
        name: "CAST",
        icon: UserCheck,
        description: "Cast contracts, schedules & contacts",
      },
      {
        id: "crew",
        name: "CREW",
        icon: Users,
        description: "Crew database, roles & availability",
        notifications: 5,
      },
      {
        id: "costume",
        name: "COSTUME",
        icon: Shirt,
        description: "Wardrobe tracking & fitting schedules",
        notifications: 1,
      },
      {
        id: "accounts",
        name: "ACCOUNTS",
        icon: DollarSign,
        description: "Financial tracking & expense management",
      },
      {
        id: "budget",
        name: "BUDGET",
        icon: Wallet,
        description: "Budget tracking, actuals & forecasts",
        notifications: 1,
      },
      {
        id: "timesheets",
        name: "TIMESHEETS",
        icon: Clock,
        description: "Crew hours, overtime & payroll data",
        notifications: 7,
      },
      {
        id: "notice-board",
        name: "NOTICE BOARD",
        icon: Megaphone,
        description: "Company-wide announcements & updates",
        notifications: 3,
      },
      {
        id: "project-chat",
        name: "PROJECT CHAT",
        icon: MessageSquare,
        description: "Real-time team messaging & channels",
        notifications: 12,
      },
      {
        id: "production-reports",
        name: "PRODUCTION REPORTS",
        icon: BarChart2,
        description: "Daily progress reports & analytics",
      },
      {
        id: "documents",
        name: "DOCUMENTS",
        icon: FolderOpen,
        description: "Contracts, releases & legal docs",
      },
      {
        id: "cloud",
        name: "CLOUD",
        icon: Cloud,
        description: "Cloud storage & file sharing",
      },
      {
        id: "eaarth-sign",
        name: "EAARTH SIGN",
        icon: PenLine,
        description: "Digital signatures & document signing",
      },
    ],
  },
  {
    id: "avatar-5",
    name: "AVATAR 5",
    subtitle: "Early Development",
    color: "#7c3aed",
    colorLight: "#f5f0ff",
    colorDark: "#3b0764",
    colorMid: "#a78bfa",
    progress: 8,
    teamCount: 42,
    apps: [
      {
        id: "script",
        name: "SCRIPT",
        icon: ScrollText,
        description: "Script versions, revisions & annotations",
        notifications: 4,
      },
      {
        id: "script-breakdown",
        name: "SCRIPT BREAKDOWN",
        icon: FileSearch,
        description: "Scene-by-scene element breakdowns",
      },
      {
        id: "storyboard",
        name: "STORYBOARD",
        icon: Film,
        description: "Visual storyboards & shot planning",
        notifications: 1,
      },
      {
        id: "concept-art",
        name: "CONCEPT ART",
        icon: Palette,
        description: "Concept artwork & visual references",
        notifications: 3,
      },
      {
        id: "budget",
        name: "BUDGET",
        icon: Wallet,
        description: "Budget tracking, actuals & forecasts",
      },
      {
        id: "accounts",
        name: "ACCOUNTS",
        icon: DollarSign,
        description: "Financial tracking & expense management",
      },
      {
        id: "notice-board",
        name: "NOTICE BOARD",
        icon: Megaphone,
        description: "Company-wide announcements & updates",
        notifications: 1,
      },
      {
        id: "project-chat",
        name: "PROJECT CHAT",
        icon: MessageSquare,
        description: "Real-time team messaging & channels",
        notifications: 6,
      },
      {
        id: "forms",
        name: "FORMS",
        icon: ClipboardList,
        description: "Custom forms, approvals & sign-offs",
      },
      {
        id: "documents",
        name: "DOCUMENTS",
        icon: FolderOpen,
        description: "Contracts, releases & legal docs",
      },
      {
        id: "cloud",
        name: "CLOUD",
        icon: Cloud,
        description: "Cloud storage & file sharing",
      },
      {
        id: "eaarth-sign",
        name: "EAARTH SIGN",
        icon: PenLine,
        description: "Digital signatures & document signing",
      },
    ],
  },
  {
    id: "scifi",
    name: "SCI-FI THRILLER",
    subtitle: "Post-Production",
    color: "#0d9488",
    colorLight: "#f0fdfa",
    colorDark: "#134e4a",
    colorMid: "#5eead4",
    progress: 100,
    teamCount: 64,
    apps: [
      {
        id: "project-calendar",
        name: "CALENDAR",
        icon: Calendar,
        description: "Master production timeline & milestones",
      },
      {
        id: "schedule",
        name: "SCHEDULE",
        icon: CalendarDays,
        description: "Overall project schedule & Gantt view",
        notifications: 1,
      },
      {
        id: "eplayer",
        name: "E PLAYER",
        icon: Play,
        description: "Dailies playback & review platform",
        notifications: 6,
      },
      {
        id: "editing",
        name: "EDITING",
        icon: Video,
        description: "Edit timeline, cuts & assembly tracking",
        notifications: 3,
      },
      {
        id: "vfx",
        name: "VFX",
        icon: Lightbulb,
        description: "VFX shot tracking & vendor management",
        notifications: 14,
      },
      {
        id: "sound-design",
        name: "SOUND DESIGN",
        icon: Headphones,
        description: "Sound effects, foley & audio mixing",
      },
      {
        id: "music-score",
        name: "MUSIC SCORE",
        icon: Music,
        description: "Original score & music licensing",
      },
      {
        id: "production-reports",
        name: "PRODUCTION REPORTS",
        icon: BarChart2,
        description: "Daily progress reports & analytics",
        notifications: 2,
      },
      {
        id: "accounts",
        name: "ACCOUNTS",
        icon: DollarSign,
        description: "Financial tracking & expense management",
      },
      {
        id: "budget",
        name: "BUDGET",
        icon: Wallet,
        description: "Budget tracking, actuals & forecasts",
      },
      {
        id: "timesheets",
        name: "TIMESHEETS",
        icon: Clock,
        description: "Crew hours, overtime & payroll data",
        notifications: 4,
      },
      {
        id: "notice-board",
        name: "NOTICE BOARD",
        icon: Megaphone,
        description: "Company-wide announcements & updates",
        notifications: 1,
      },
      {
        id: "project-chat",
        name: "PROJECT CHAT",
        icon: MessageSquare,
        description: "Real-time team messaging & channels",
        notifications: 7,
      },
      {
        id: "documents",
        name: "DOCUMENTS",
        icon: FolderOpen,
        description: "Contracts, releases & legal docs",
      },
      {
        id: "cloud",
        name: "CLOUD",
        icon: Cloud,
        description: "Cloud storage & file sharing",
      },
      {
        id: "eaarth-sign",
        name: "EAARTH SIGN",
        icon: PenLine,
        description: "Digital signatures & document signing",
      },
    ],
  },
  {
    id: "documentary",
    name: "DOCUMENTARY",
    subtitle: "In Production",
    color: "#d97706",
    colorLight: "#fffbeb",
    colorDark: "#78350f",
    colorMid: "#fbbf24",
    progress: 45,
    teamCount: 32,
    apps: [
      {
        id: "project-calendar",
        name: "CALENDAR",
        icon: Calendar,
        description: "Master production timeline & milestones",
        notifications: 2,
      },
      {
        id: "call-sheets",
        name: "CALL SHEETS",
        icon: FileText,
        description: "Daily call sheets & crew notifications",
        notifications: 1,
      },
      {
        id: "shooting-schedule",
        name: "SHOOTING SCHEDULE",
        icon: Clapperboard,
        description: "Day-by-day shooting plan & scene order",
      },
      {
        id: "script",
        name: "SCRIPT",
        icon: ScrollText,
        description: "Script versions, revisions & annotations",
      },
      {
        id: "script-breakdown",
        name: "SCRIPT BREAKDOWN",
        icon: FileSearch,
        description: "Scene-by-scene element breakdowns",
      },
      {
        id: "locations",
        name: "LOCATIONS",
        icon: MapPin,
        description: "Location scouting, permits & maps",
        notifications: 3,
      },
      {
        id: "interviews",
        name: "INTERVIEWS",
        icon: Mic,
        description: "Interview scheduling & transcriptions",
        notifications: 5,
      },
      {
        id: "camera",
        name: "CAMERA",
        icon: Camera,
        description: "Camera equipment & lens tracking",
      },
      {
        id: "animals",
        name: "ANIMALS",
        icon: PawPrint,
        description: "Animal wrangling schedules & welfare",
      },
      {
        id: "transport",
        name: "TRANSPORT",
        icon: Truck,
        description: "Vehicle scheduling & logistics",
      },
      {
        id: "crew",
        name: "CREW",
        icon: Users,
        description: "Crew database, roles & availability",
      },
      {
        id: "accounts",
        name: "ACCOUNTS",
        icon: DollarSign,
        description: "Financial tracking & expense management",
      },
      {
        id: "budget",
        name: "BUDGET",
        icon: Wallet,
        description: "Budget tracking, actuals & forecasts",
      },
      {
        id: "timesheets",
        name: "TIMESHEETS",
        icon: Clock,
        description: "Crew hours, overtime & payroll data",
        notifications: 6,
      },
      {
        id: "notice-board",
        name: "NOTICE BOARD",
        icon: Megaphone,
        description: "Company-wide announcements & updates",
      },
      {
        id: "project-chat",
        name: "PROJECT CHAT",
        icon: MessageSquare,
        description: "Real-time team messaging & channels",
        notifications: 9,
      },
      {
        id: "production-reports",
        name: "PRODUCTION REPORTS",
        icon: BarChart2,
        description: "Daily progress reports & analytics",
      },
      {
        id: "forms",
        name: "FORMS",
        icon: ClipboardList,
        description: "Custom forms, approvals & sign-offs",
      },
      {
        id: "documents",
        name: "DOCUMENTS",
        icon: FolderOpen,
        description: "Contracts, releases & legal docs",
      },
      {
        id: "cloud",
        name: "CLOUD",
        icon: Cloud,
        description: "Cloud storage & file sharing",
      },
      {
        id: "research",
        name: "RESEARCH",
        icon: BookOpen,
        description: "Research materials & reference library",
      },
      {
        id: "gallery",
        name: "GALLERY",
        icon: Image,
        description: "Photo gallery & visual references",
      },
      {
        id: "eaarth-sign",
        name: "EAARTH SIGN",
        icon: PenLine,
        description: "Digital signatures & document signing",
      },
    ],
  },
  {
    id: "horror",
    name: "HORROR REBOOT",
    subtitle: "Development",
    color: "#e11d48",
    colorLight: "#fff1f2",
    colorDark: "#881337",
    colorMid: "#fb7185",
    progress: 18,
    teamCount: 14,
    apps: [
      {
        id: "script",
        name: "SCRIPT",
        icon: ScrollText,
        description: "Script versions, revisions & annotations",
        notifications: 6,
      },
      {
        id: "script-breakdown",
        name: "SCRIPT BREAKDOWN",
        icon: FileSearch,
        description: "Scene-by-scene element breakdowns",
      },
      {
        id: "storyboard",
        name: "STORYBOARD",
        icon: Film,
        description: "Visual storyboards & shot planning",
        notifications: 2,
      },
      {
        id: "concept-art",
        name: "CONCEPT ART",
        icon: Palette,
        description: "Concept artwork & visual references",
        notifications: 1,
      },
      {
        id: "casting-calls",
        name: "CASTING CALLS",
        icon: Star,
        description: "Casting sessions & talent management",
        notifications: 3,
      },
      {
        id: "cast",
        name: "CAST",
        icon: UserCheck,
        description: "Cast contracts, schedules & contacts",
      },
      {
        id: "locations",
        name: "LOCATIONS",
        icon: MapPin,
        description: "Location scouting, permits & maps",
      },
      {
        id: "budget",
        name: "BUDGET",
        icon: Wallet,
        description: "Budget tracking, actuals & forecasts",
      },
      {
        id: "accounts",
        name: "ACCOUNTS",
        icon: DollarSign,
        description: "Financial tracking & expense management",
      },
      {
        id: "notice-board",
        name: "NOTICE BOARD",
        icon: Megaphone,
        description: "Company-wide announcements & updates",
      },
      {
        id: "project-chat",
        name: "PROJECT CHAT",
        icon: MessageSquare,
        description: "Real-time team messaging & channels",
        notifications: 4,
      },
      {
        id: "forms",
        name: "FORMS",
        icon: ClipboardList,
        description: "Custom forms, approvals & sign-offs",
      },
      {
        id: "documents",
        name: "DOCUMENTS",
        icon: FolderOpen,
        description: "Contracts, releases & legal docs",
      },
      {
        id: "cloud",
        name: "CLOUD",
        icon: Cloud,
        description: "Cloud storage & file sharing",
      },
      {
        id: "eaarth-sign",
        name: "EAARTH SIGN",
        icon: PenLine,
        description: "Digital signatures & document signing",
      },
    ],
  },
];

export const studios = [
  {
    id: "lightstorm",
    name: "LIGHTSTORM ENTERTAINMENT",
    logo: "LE",
    color: "#7c3aed",
    colorLight: "#f5f0ff",
    colorDark: "#3b0764",
    plan: "blockbuster",
    billingCycle: "annual",
    memberCount: 334,
    projects: [projects[0], projects[1]],
  },
  {
    id: "neon-pictures",
    name: "NEON PICTURES",
    logo: "NP",
    color: "#0d9488",
    colorLight: "#f0fdfa",
    colorDark: "#134e4a",
    plan: "studio",
    billingCycle: "monthly",
    memberCount: 96,
    projects: [projects[2], projects[3]],
  },
  {
    id: "midnight-films",
    name: "MIDNIGHT FILMS",
    logo: "MF",
    color: "#e11d48",
    colorLight: "#fff1f2",
    colorDark: "#881337",
    plan: "indie",
    billingCycle: "weekly",
    memberCount: 14,
    projects: [projects[4]],
  },
];

export const DEFAULT_STYLE = {
  accentColor: "",
  cardStyle: "elevated",
  borderRadius: "lg",
  iconStyle: "filled",
  appNameCase: "upper",
  themeMode: "system",
  saturation: "normal",
  headerStyle: "standard",
};

export const DEFAULT_LAYOUT = {
  gridCols: 4,
  cardSize: "default",
  sidebarDefault: "closed",
  showProgress: true,
  showTeamCount: true,
  showNotifBadges: true,
  widgetColumns: 2,
  tabBarPosition: "top",
  appSortOrder: "default",
  showAppDescriptions: false,
};

export const DEFAULT_APP_SETTINGS = {
  enabled: true,
  notifications: true,
  visibility: "everyone",
};

export const COLOR_PRESETS = [
  { label: "Purple", value: "#7c3aed" },
  { label: "Blue", value: "#2563eb" },
  { label: "Teal", value: "#0d9488" },
  { label: "Amber", value: "#d97706" },
  { label: "Rose", value: "#e11d48" },
  { label: "Emerald", value: "#059669" },
  { label: "Indigo", value: "#4f46e5" },
  { label: "Pink", value: "#db2777" },
  { label: "Cyan", value: "#0891b2" },
  { label: "Orange", value: "#ea580c" },
  { label: "Slate", value: "#475569" },
  { label: "Violet", value: "#8b5cf6" },
];

export const SETTINGS_MENU = [
  {
    id: "project-settings",
    label: "Project Settings",
    icon: Settings2,
    children: [
      { id: "details", label: "Details", icon: Settings2 },
      { id: "contacts", label: "Contacts", icon: Contact },
      { id: "dates", label: "Dates", icon: CalendarDays },
    ],
  },
  {
    id: "rates-rules",
    label: "Rates & Rules",
    icon: Bookmark,
    children: [
      { id: "rates-project", label: "Project", icon: Bookmark },
      { id: "rates-crew", label: "Standard Crew", icon: Users },
      { id: "rates-construction", label: "Construction", icon: Building },
      { id: "rates-places", label: "Places", icon: MapPin },
      { id: "rates-departments", label: "Departments", icon: Users },
    ],
  },
  {
    id: "contracts-templates",
    label: "Contracts & Templates",
    icon: FileBox,
    children: [
      { id: "doc-signers", label: "Signatures & Workflow", icon: FileCheck },
      { id: "contracts-forms", label: "Contracts & Forms", icon: FileText },
    ],
  },
  { id: "admin", label: "Admin", icon: LockKeyhole },
  { id: "custom", label: "Custom", icon: Sliders },
  { id: "notifications", label: "Notifications", icon: Bell },
  { id: "timecard", label: "Timecard", icon: Clock },
  { id: "subscriptions", label: "Subscriptions", icon: CreditCard },
  { id: "style", label: "Design & Style", icon: Palette },
  { id: "layout", label: "Layout", icon: LayoutGrid },
  { id: "apps", label: "App Settings", icon: AppWindow },
  { id: "chat", label: "Chat", icon: MessageCircle },
  { id: "calendar", label: "Calendar", icon: CalendarDays },
  { id: "ai-knowledge-base", label: "AI Knowledge Base", icon: Brain },
];

export const ALL_TAB_IDS = SETTINGS_MENU.flatMap((e) =>
  "children" in e ? e.children.map((c) => c.id) : [e.id],
);

export const ALL_FLAT_ITEMS = SETTINGS_MENU.flatMap((e) =>
  "children" in e ? e.children : [e],
);