import { Clock } from "lucide-react";

export function ApprovalHistory() {
  const now = new Date();

  return (
    <div className="bg-white rounded-xl border border-neutral-200/80 p-2 shadow-[0_1px_3px_rgba(0,0,0,0.04)]">
      <div className="flex items-center gap-1.5 mb-1.5">
        <Clock className="h-3 w-3 text-neutral-500" />
        <h3 className="text-[11px] font-semibold text-neutral-800 tracking-wide uppercase">Approval History</h3>
      </div>
      <div className="space-y-1.5">
        <div className="flex items-start gap-2">
          <div className="mt-1 h-2 w-2 rounded-full bg-emerald-500 shrink-0 ring-2 ring-emerald-100" />
          <div className="text-[10px]">
            <p className="text-neutral-700">
              <span className="font-semibold">Offer Created</span>
              <span className="text-neutral-400 mx-1.5">—</span>
              Generated by Production
            </p>
            <p className="text-neutral-400 mt-0.5">
              {now.toLocaleDateString("en-GB", { day: "numeric", month: "short", year: "numeric" })} at{" "}
              {now.toLocaleTimeString("en-GB", { hour: "2-digit", minute: "2-digit" })}
            </p>
          </div>
        </div>
        <div className="flex items-start gap-2">
          <div className="mt-1 h-2 w-2 rounded-full bg-amber-400 shrink-0 ring-2 ring-amber-100" />
          <div className="text-[10px]">
            <p className="text-neutral-700">
              <span className="font-semibold">Pending Approval</span>
              <span className="text-neutral-400 mx-1.5">—</span>
              Awaiting department head sign-off
            </p>
            <p className="text-neutral-400 mt-0.5">Waiting...</p>
          </div>
        </div>
      </div>
    </div>
  );
}