import { Clock } from "lucide-react";

const fmtDateTime = (d) => {
  if (!d) return null;
  const date = new Date(d);
  return `${date.toLocaleDateString("en-GB", {
    day: "numeric", month: "short", year: "numeric",
  })} at ${date.toLocaleTimeString("en-GB", { hour: "2-digit", minute: "2-digit" })}`;
};

// Map each status transition to a human-readable event
function buildEvents(offer) {
  if (!offer) return [];
  const tl = offer.timeline || {};
  const events = [];

  if (offer.createdAt) {
    events.push({
      label: "Offer Created",
      description: "Generated by Production",
      timestamp: offer.createdAt,
      color: "bg-emerald-500 ring-emerald-100",
    });
  }
  if (tl.sentToCrewAt) {
    events.push({
      label: "Sent to Crew",
      description: `Sent to ${offer.recipient?.fullName || "crew member"}`,
      timestamp: tl.sentToCrewAt,
      color: "bg-blue-500 ring-blue-100",
    });
  }
  if (tl.crewViewedAt) {
    events.push({
      label: "Viewed by Crew",
      description: `${offer.recipient?.fullName || "Crew"} opened the offer`,
      timestamp: tl.crewViewedAt,
      color: "bg-sky-400 ring-sky-100",
    });
  }
  if (tl.crewAcceptedAt) {
    events.push({
      label: "Crew Accepted",
      description: `${offer.recipient?.fullName || "Crew"} accepted the offer`,
      timestamp: tl.crewAcceptedAt,
      color: "bg-emerald-500 ring-emerald-100",
    });
  }
  if (offer.status === "NEEDS_REVISION" && tl.sentToCrewAt) {
    events.push({
      label: "Revision Requested",
      description: "Crew requested changes",
      timestamp: offer.updatedAt,
      color: "bg-orange-400 ring-orange-100",
    });
  }
  if (tl.productionCheckCompletedAt) {
    events.push({
      label: "Production Check",
      description: "Approved by Production",
      timestamp: tl.productionCheckCompletedAt,
      color: "bg-violet-500 ring-violet-100",
    });
  }
  if (tl.accountsCheckCompletedAt) {
    events.push({
      label: "Accounts Check",
      description: "Approved by Accounts",
      timestamp: tl.accountsCheckCompletedAt,
      color: "bg-indigo-500 ring-indigo-100",
    });
  }
  if (tl.pendingCrewSignatureAt) {
    events.push({
      label: "Sent for Signature",
      description: "Contract sent for crew signature",
      timestamp: tl.pendingCrewSignatureAt,
      color: "bg-purple-500 ring-purple-100",
    });
  }
  if (tl.crewSignedAt) {
    events.push({
      label: "Crew Signed",
      description: "Contract signed by crew",
      timestamp: tl.crewSignedAt,
      color: "bg-emerald-500 ring-emerald-100",
    });
  }
  if (tl.upmSignedAt) {
    events.push({
      label: "UPM Signed",
      description: "Contract signed by UPM",
      timestamp: tl.upmSignedAt,
      color: "bg-emerald-500 ring-emerald-100",
    });
  }
  if (tl.fcSignedAt) {
    events.push({
      label: "FC Signed",
      description: "Contract signed by Finance Controller",
      timestamp: tl.fcSignedAt,
      color: "bg-emerald-500 ring-emerald-100",
    });
  }
  if (tl.studioSignedAt) {
    events.push({
      label: "Studio Signed",
      description: "Contract fully executed",
      timestamp: tl.studioSignedAt,
      color: "bg-emerald-500 ring-emerald-100",
    });
  }
  if (tl.completedAt) {
    events.push({
      label: "Completed",
      description: "Contract completed",
      timestamp: tl.completedAt,
      color: "bg-emerald-600 ring-emerald-100",
    });
  }
  if (tl.cancelledAt) {
    events.push({
      label: "Cancelled",
      description: "Offer was cancelled",
      timestamp: tl.cancelledAt,
      color: "bg-red-500 ring-red-100",
    });
  }

  return events;
}

export function ApprovalHistory({ offer }) {
  const events = buildEvents(offer);

  // Nothing to show — render nothing at all
  if (events.length === 0) return null;

  return (
    <div className="bg-white rounded-xl border border-neutral-200/80 p-2 shadow-[0_1px_3px_rgba(0,0,0,0.04)]">
      <div className="flex items-center gap-1.5 mb-1.5">
        <Clock className="h-3 w-3 text-neutral-500" />
        <h3 className="text-[11px] font-semibold text-neutral-800 tracking-wide uppercase">
          Approval History
        </h3>
      </div>

      <div className="space-y-1.5">
        {events.map((ev, i) => (
          <div key={i} className="flex items-start gap-2">
            <div className={`mt-1 h-2 w-2 rounded-full shrink-0 ring-2 ${ev.color}`} />
            <div className="text-[10px]">
              <p className="text-neutral-700">
                <span className="font-semibold">{ev.label}</span>
                <span className="text-neutral-400 mx-1.5">—</span>
                {ev.description}
              </p>
              {ev.timestamp && (
                <p className="text-neutral-400 mt-0.5">{fmtDateTime(ev.timestamp)}</p>
              )}
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}