import { useState } from "react";
import { OfferHeader } from "./OfferHeader";
import { RecipientSection } from "./RecipientSection";
import { OfferDetailsSection } from "./OfferDetailsSection";
import { ContractTermsSection } from "./ContractTermsSection";
import { SalaryTable } from "./FeeStructure/SalaryTable";
import { OvertimeTable } from "./FeeStructure/OvertimeTable";
import { AllowancesGrid } from "./FeeStructure/AllowancesGrid";
import { ApprovalHistory } from "./ApprovalHistory";
import { HighlightField } from "../shared/HighlightField";
// ContractDocument intentionally not imported — no preview on Create Offer.
// Bundle is generated by backend after crew accepts.

const allowanceLabelMap = [
  { key: "boxRental",  label: "Box Rental"  },
  { key: "computer",   label: "Computer"    },
  { key: "software",   label: "Software"    },
  { key: "equipment",  label: "Equipment"   },
  { key: "vehicle",    label: "Vehicle"     },
  { key: "mobile",     label: "Mobile"      },
  { key: "living",     label: "Living"      },
  { key: "perDiem1",   label: "Per Diem 1"  },
  { key: "perDiem2",   label: "Per Diem 2"  },
  { key: "breakfast",  label: "Breakfast"   },
  { key: "lunch",      label: "Lunch"       },
  { key: "dinner",     label: "Dinner"      },
  { key: "fuel",       label: "Fuel"        },
  { key: "mileage",    label: "Mileage"     },
];

export function CreateOfferLayout({
  // ── form / preview data ──
  data,
  activeField,
  onFieldClick,
  onFieldFocus,
  onFieldBlur,
  calculatedRates,
  engineSettings,
  salaryBudgetCodes,
  setSalaryBudgetCodes,
  salaryTags,
  setSalaryTags,
  overtimeBudgetCodes,
  setOvertimeBudgetCodes,
  overtimeTags,
  setOvertimeTags,
  allowances,
  // FIX: accept projectSettings so ContractDocument can render dynamic values
  projectSettings = null,
  // ── offer object from backend (for real dates / timeline) ──
  offer = null,
  // ── display flags ──
  initialOfferCollapsed = false,
  isDocumentLocked = false,
  hideContractDocument = false,
  hideOfferSections = false,
  // ── signing ──
  signatures = {},
  activeSigningRole = null,
  onSignatureClick,
}) {
  const [offerCollapsed, setOfferCollapsed] = useState(initialOfferCollapsed);

  const getCurrencySymbol = () => {
    const map = { GBP:"£", USD:"$", EUR:"€", AUD:"A$", CAD:"C$", NZD:"NZ$", DKK:"kr", ISK:"kr" };
    return map[data.currency] || "£";
  };
  const cs = getCurrencySymbol();

  const enabledAllowances = allowanceLabelMap.filter((a) => allowances[a.key]?.enabled);

  // FIX: read notes from data.notes.* (matches offer model)
  const notes          = data.notes          || {};
  const otherDeal      = notes.otherDealProvisions || data.otherDealProvisions || "";
  const additionalNotes = notes.additionalNotes   || data.additionalNotes    || "";

  return (
    <div className="bg-purple-50/30 uppercase">
      {!hideOfferSections && (
        <OfferHeader
          data={data}
          offer={offer}
          offerCollapsed={offerCollapsed}
          onToggleCollapse={() => setOfferCollapsed((p) => !p)}
        />
      )}

      <div className="px-3 py-2.5 space-y-2">
        {!offerCollapsed && !hideOfferSections && (
          <>
            {/* Recipient + Offer Details */}
            <div className="grid grid-cols-2 gap-2">
              <RecipientSection
                data={data}
                activeField={activeField}
                onFieldClick={onFieldClick}
              />
              <OfferDetailsSection
                data={data}
                activeField={activeField}
                onFieldClick={onFieldClick}
              />
            </div>

            {/* Contract Terms */}
            <ContractTermsSection
              data={data}
              activeField={activeField}
              onFieldClick={onFieldClick}
              engineSettings={engineSettings}
            />

            {/* Other Deal Provisions & Internal Notes */}
            {(otherDeal || additionalNotes) && (
              <div className="grid grid-cols-2 gap-2">
                {otherDeal && (
                  <div className="bg-amber-50/80 rounded-lg border border-amber-200/60 px-2 py-1">
                    <div className="flex items-center gap-1">
                      <div className="w-[2px] h-3 bg-amber-400 rounded-full" />
                      <p className="text-[10px] font-semibold text-amber-800 tracking-wide uppercase">
                        Other Deal Provisions
                      </p>
                    </div>
                    <HighlightField
                      fieldName="notes.otherDealProvisions"
                      active={activeField === "notes.otherDealProvisions" || activeField === "otherDealProvisions"}
                      onClick={onFieldClick}
                    >
                      <p className="text-[10px] text-neutral-700 leading-snug">
                        {otherDeal}
                      </p>
                    </HighlightField>
                  </div>
                )}
                {additionalNotes && (
                  <div className="bg-purple-50/60 rounded-lg border border-purple-200/60 px-2 py-1">
                    <div className="flex items-center gap-1">
                      <div className="w-[2px] h-3 bg-purple-400 rounded-full" />
                      <p className="text-[10px] font-semibold text-purple-800 tracking-wide uppercase">
                        Internal Notes
                      </p>
                    </div>
                    <HighlightField
                      fieldName="notes.additionalNotes"
                      active={activeField === "notes.additionalNotes" || activeField === "additionalNotes"}
                      onClick={onFieldClick}
                    >
                      <p className="text-[10px] text-neutral-600 leading-snug">
                        {additionalNotes}
                      </p>
                    </HighlightField>
                  </div>
                )}
              </div>
            )}

            {/* Fee Structure */}
            <div>
              <div className="flex items-center justify-between mb-1.5">
                <div className="flex items-center gap-2">
                  <div className="w-[3px] h-4 bg-purple-600 rounded-full" />
                  <h3 className="text-[11px] font-semibold text-purple-900 tracking-wide uppercase">
                    Fee Structure
                  </h3>
                </div>
                <span className="text-[9px] text-neutral-400 font-medium">
                  Base {cs}{data.feePerDay || "0.00"}/day ·{" "}
                  {(engineSettings.holidayUplift * 100).toFixed(2)}% holiday ·{" "}
                  {engineSettings.agreementMode}
                </span>
              </div>

              <div className="grid grid-cols-2 gap-2 items-start">
                <SalaryTable
                  calculatedRates={calculatedRates}
                  salaryBudgetCodes={salaryBudgetCodes}
                  setSalaryBudgetCodes={setSalaryBudgetCodes}
                  salaryTags={salaryTags}
                  setSalaryTags={setSalaryTags}
                  activeField={activeField}
                  onFieldFocus={onFieldFocus}
                  onFieldBlur={onFieldBlur}
                  currencySymbol={cs}
                />
                <OvertimeTable
                  calculatedRates={calculatedRates}
                  overtimeBudgetCodes={overtimeBudgetCodes}
                  setOvertimeBudgetCodes={setOvertimeBudgetCodes}
                  overtimeTags={overtimeTags}
                  setOvertimeTags={setOvertimeTags}
                  activeField={activeField}
                  onFieldFocus={onFieldFocus}
                  onFieldBlur={onFieldBlur}
                  currencySymbol={cs}
                  overtimeMode={data.overtime}
                />
              </div>

              <AllowancesGrid
                enabledAllowances={enabledAllowances}
                allowances={allowances}
                activeField={activeField}
                currencySymbol={cs}
              />
            </div>

            {/* Approval History — only renders when offer has real timeline data */}
            <ApprovalHistory offer={offer} />
          </>
        )}

        {/* ── No document preview on Create Offer ──
            Contract bundle is generated after crew accepts.
            The deal document preview has been intentionally removed.
        */}
      </div>
    </div>
  );
}